### PR TITLE
Update due to Keras and recipes package changes

### PR DESCRIPTION
**Pull request by SaJaToGu**
Update due to Keras and recipes package changes and initial errors due to missing library statements.
library(readr)
library(ggplot2)
library(forcats) are missing in customer_churn.R
bake parameter from newdata => new_data
keras function model_type.keras.models.Sequential => model_type.keras.engine.sequential.Sequential

library(rsample)
library(recipes)
library(yardstick)
library(readr)
library(ggplot2)
library(forcats) missing in customer_churn.Rmd

### CODE REVIEW

**Comment by jjallaire** [comment]
@dfalbel Could you take a look at this?

**Comment by dfalbel** [comment]
Looks good to me - also works with TF2. Can you give write access to this repo?

**Comment by jjallaire** [comment]
Just gave you access....thanks!

**Comment by SaJaToGu** [comment]
You do not publish the change to the shiny app to solve the issue there?

**Pull request merged**
